2024OSPP——基于AI网关实现AI模型的轻量化部署
higress-group/envoy pull request #1
Opened 2024-08-28 11:09 UTC by YJQ1101

##### 简介
该功能实现在诸如个人电脑、普通的云主机上基于AI模型提供AI Web应用能力，具体来说，支持从本地文件加载模型，并解析HTTP请求，调用模型生成结果响应。https://summer-ospp.ac.cn/org/prodetail/241f80032?lang=zh&list=pro

##### 实现
实现了一个 HTTP Filter，该filter会解析推理请求，并调用异步推理线程实现推理过程，同时给该异步线程一个回调函数，实现envoy的流式传输。

##### 编译与运行
```
bazel build //contrib/exe:envoy-static #编译
bazel-bin/contrib/exe/envoy-static -c "envoy.yaml"  --concurrency 1 #运行
```

##### 配置使用
filter级配置：
```
- name: envoy.filters.http.llm_inference
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.llm_inference.v3.modelParameter
    n_threads : 100
    n_parallel : 5
    modelpath: {
      "qwen2": "/home/yuanjq/model/qwen2-7b-instruct-q5_k_m.gguf",
      "llama3": "/home/yuanjq/model/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
      "bge": "/home/yuanjq/model/bge-small-zh-v1.5-f32.gguf"
    }

```
n_threads: 表示推理线程能用的最大线程数
n_parallel: 表示推理服务的最大请求数
modelpath: 表示模型本地路径

router级配置：
```
route_config:
  name: route
  virtual_hosts:
  - name: llm_inference_service
    domains: ["api.openai.com"]
    routes:
    - match:
        prefix: "/v1/chat/completions"
      typed_per_filter_config:
        envoy.filters.http.llm_inference:
          "@type": type.googleapis.com/envoy.extensions.filters.http.llm_inference.v3.modelChosen
          usemodel: "qwen2"
          first_byte_timeout : 4
          inference_timeout : 90
          embedding : false
      direct_response:
        status: 504
        body:
          inline_string: "inference timeout"
```
usemodel: 表示使用的模型，模型名字与modelpath里面设置的要对应
first_byte_timeout: 表示首字节超时时间
inference_timeout: 表示总推理超时时间
embedding: 表示该模型是否是embedding模型

##### 支持模型
- llama3.1 (https://huggingface.co/lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF)
- qwen2 (https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF)
- bge https://huggingface.co/CompendiumLabs/bge-small-zh-v1.5-gguf

2024-08-28 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/higress-group/envoy?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/higress-group/envoy?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/higress-group/envoy?pullRequest=1) it.</sub>

2024-09-11 09:38 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/config.cc
> +    model_Chosen_ = config->modelChosen();
```suggestion
    model_chosen_ = config->modelChosen();
```

2024-09-11 09:39 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/config.cc
> +      ctx = inference->load(inference, config->modelParameter(), model_Chosen_, modelpath[model_Chosen_.model_name]);
```suggestion
    if (modelpath.contains(model_chosen_.model_name)) {
      ctx = inference->load(inference, config->modelParameter(), model_chosen_, modelpath[model_chosen_.model_name]);
```

2024-09-11 09:40 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/config.h
> +  ModelChosen model_Chosen_;
```suggestion
  ModelChosen model_chosen_;
```

2024-09-11 09:46 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/llm_inference_filter.cc
> +    : modelParameter_{proto_config.n_threads(), proto_config.n_parallel()},
变量命名都注意一下，成员变量都用下划线风格，不用驼峰

2024-09-11 10:02 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/config.cc
> +    absl::MutexLock lock(&mu_);
应该只会在配置解析阶段发生load？那都是是主线程做的，不需要加锁

2024-09-11 10:09 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/config.cc
> +    if (modelpath.contains(model_Chosen_.model_name)) {
如果多个路由用了不同chosen，这里会有问题，只会加载最后一个model。我觉得这里可以直接load所有配置的模型。问题不大的。因为是用户自己配置的。

2024-09-23 02:57 UTC, johnlanni requested changes
可以加个 README.md 说明下 filter 的配置使用方式，使用注意事项等。性能也建议和ollama对比一下，看下相同模型相同问题相同并发下的资源开销对比，响应延时对比。

2024-09-23 02:57 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/config.cc
> +              const std::string& model_name, const std::string& model_path, bool embedding) {
embedding 用参数来区分不太好，我建议用独立的函数区分，loadLLM, loadEmbedding

context 里同理

2024-09-23 02:57 UTC, johnlanni commented on contrib/llm_inference/filters/http/source/inference/inference_context.cc
> +        LOG_INFO(buffer, {
这个 LOG_INFO 是定义在 llama.cpp 里的吗？要用这个的目的是什么，是否可以改成用 ENVOY_LOG

2024-09-23 05:59 UTC, YJQ1101 commented on contrib/llm_inference/filters/http/source/inference/inference_context.cc
> +        LOG_INFO(buffer, {
是的，LOG_INFO是 llama.cpp 里面用的，应该可以把它替换成ENVOY_LOG的形式

2024-09-27 03:03 UTC, johnlanni requested changes

2024-09-27 03:03 UTC, johnlanni commented on contrib/llm_inference/filters/http/README.md
> +并发请求数     |  项目     | Ollama
```suggestion
并发请求数     |  LLM Inference Filter     | Ollama
```

2024-09-27 03:03 UTC, johnlanni commented on contrib/llm_inference/filters/http/README.md
> +并发请求数     |  项目     | Ollama
```suggestion
并发请求数     |  LLM Inference Filter      | Ollama
```

2024-09-27 03:03 UTC, johnlanni commented on contrib/llm_inference/filters/http/README.md
> +并发请求数     |  项目     | Ollama
```suggestion
并发请求数     |  LLM Inference Filter      | Ollama
```

2024-09-27 03:03 UTC, johnlanni commented on contrib/llm_inference/filters/http/README.md
> +- **响应延迟**
这个应该是指首 token 延迟？

2024-09-27 03:03 UTC, johnlanni commented on contrib/llm_inference/filters/http/README.md
> +- **内存资源开销**
是否加一下 CPU 开销对比

2024-09-27 03:06 UTC, johnlanni requested changes

2024-09-27 03:06 UTC, johnlanni commented on contrib/llm_inference/filters/http/README.md
> +n_parallel: 表示推理服务的最大并行请求数
下面测试的有8个并行请求，这里是否配置为8比较合理？还有个疑问是这里既然配置为5，那么8个并行请求的时候，应该响应延迟会明显增大，但实际看并没有？

2024-09-28 10:19 UTC, YJQ1101 commented on contrib/llm_inference/filters/http/README.md
> +- **响应延迟**
是的，是首 token 延迟

2024-09-28 10:23 UTC, YJQ1101 commented on contrib/llm_inference/filters/http/README.md
> +n_parallel: 表示推理服务的最大并行请求数
这个只是示例，测的时候就是n_parallel=1、4、8这么测的

2024-10-08 02:40 UTC, johnlanni approved these changes
LGTM

2024-10-08 02:40 UTC, merged